apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  project: techtrends
  source:
    repoURL: 'https://github.com/snsd2912/TechTrend.git'
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
